name: Build, Release and Publish APT Repo

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev fakeroot make

      - name: Build .deb package
        run: |
          make clean build
          ls -lh *.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcherhub-deb
          path: "*.deb"

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: launcherhub-deb
          path: repo

      - name: Generate APT repo metadata
        run: |
          cd repo
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz

      - name: Upload APT repo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: repo/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
